#!/usr/bin/env Rscript

# This script is a TEMPLATE for estimating the relative detection based on the breadth of coverage (detection) of genomes by sample.
# It utilices the package "picante" from R-script

# the INPUT_FILE is the name of the detecttion.txt file generated by anvi'o during the summary step for each site
# the OUTPUT_FILE is the name of the relAbsBreadth.txt given by the user

# load package
library(picante)

# read mean coverage file
meanCov <- read.csv("INPUT_FILE", header = TRUE, row.names = 1, sep = "\t")

# transpose mean coverage matrix
meanCovT <- t(meanCov)

# transform mean coverages to relative abundances across samples
# mean coverage of a genome / sum of mean coverages of all genomes in a sample
relAbsT <- decostand(meanCovT, method = "total")

# transpose relative abundance matrix
relAbs <- t(relAbsT)

# multiply by 100
relAbs <- 100*relAbs 

# save matrix
write.table(data.frame("Genome_ID"=rownames(relAbs),relAbs), file = "OUTPUT_FILE", sep = "\t", quote = FALSE, row.names=FALSE)
