---
title: "Untitled"
author: "J. J. Giacomini"
date: "2023-11-23"
output: html_document
---

When running the decompose and summarize script on the merged profiles, I discovered that the project report file had a major error where the contigs and splits associated with meningitids and gonorrhoea genomes had incorrect suffixes for their respective genome IDs. They were accidentally based on their original genome IDs, which ranged from 0 to 4000, instead of their updated IDs which ranged from 0621 to 0641. For exmaple, whne looking at the project report file, for rows in the first column within the range P_0003_Neisseriaceae_000000013964 to P_0003_Neisseriaceae_000000014103, the corresponding rows in the second column shoudl have suffixes of G_0621, but instead have G_0075. Similarly, for rows in the first column within the range P_0003_Neisseriaceae_000000014428 to P_0003_Neisseriaceae_000000014515, the corresponding rows in the second column should be changed from G_0121 to G_0625. Also, for rows in the first column within the range P_0003_Neisseriaceae_000000014516 to P_0003_Neisseriaceae_000000014592, the corresponding rows in the second column should be changed from G_0139 to G_0626.

Using Python we can perform these edits to the project report file and save the modified content to a new file.

```{python, eval=FALSE}

# Let's read the uploaded file and display the first few lines to understand its structure
file_path = '/mnt/data/P_0003_Neisseriaceae.report_copy.tsv'

# Reading and displaying the first few lines of the file
with open(file_path, 'r') as file:
    lines = file.readlines()

# Display the first 10 lines to understand the structure
lines[:10]

```



```{python, eval=FALSE}

def modify_second_column(row, prefix_range, new_prefix, start_suffix):
    """
    Modify the second column of the row if the first column is within the specified range.

    :param row: A tuple (col1, col2) representing the two columns of the row.
    :param prefix_range: A tuple (start, end) representing the range of values for the first column.
    :param new_prefix: The new prefix for the second column.
    :param start_suffix: The starting suffix number for the new second column values.
    :return: The modified row.
    """
    col1, col2 = row
    start, end = prefix_range

    # Check if the first column is within the specified range
    if start <= col1 <= end:
        # Extract the numeric suffix of the second column
        suffix = int(col2.split('_')[-1])
        # Calculate the new suffix by adding the start suffix and adjusting for zero-based index
        new_suffix = start_suffix + suffix - 1
        # Construct the new second column value
        col2 = f"{new_prefix}_{new_suffix:012d}"

    return col1, col2


def process_file(file_path):
    modified_lines = []

    # Define the ranges and new prefixes for modification
    modifications = [
        (("P_0003_Neisseriaceae_000000013964", "P_0003_Neisseriaceae_000000014103"), "G_0621", 1),
        (("P_0003_Neisseriaceae_000000014428", "P_0003_Neisseriaceae_000000014515"), "G_0625", 1),
        (("P_0003_Neisseriaceae_000000014516", "P_0003_Neisseriaceae_000000014592"), "G_0626", 1)
    ]

    with open(file_path, 'r') as file:
        for line in file:
            # Split the line into two columns
            col1, col2 = line.strip().split('\t')

            # Apply modifications based on the defined rules
            for prefix_range, new_prefix, start_suffix in modifications:
                col1, col2 = modify_second_column((col1, col2), prefix_range, new_prefix, start_suffix)

            # Reconstruct the line and add it to the modified lines list
            modified_lines.append(f"{col1}\t{col2}\n")

    return modified_lines


# Process the file
modified_content = process_file(file_path)

# Preview the first 10 modified lines
modified_content[:10]

```

The modifications have been applied to the file. To ensure that the changes are correct, I will now check a few lines from each of the specified ranges. This will help confirm that the edits were made as per your requirements. 

The checks confirm that the modifications have been applied correctly:

For rows in the range P_0003_Neisseriaceae_000000013964 to P_0003_Neisseriaceae_000000014103, the second column has been changed from G_0075 to G_0621, with suffixes ranging from 000000000001 to 000000000140.

For rows in the range P_0003_Neisseriaceae_000000014428 to P_0003_Neisseriaceae_000000014515, the second column has been changed from G_0121 to G_0625, with suffixes ranging from 000000000001 to 000000000088.

For rows in the range P_0003_Neisseriaceae_000000014516 to P_0003_Neisseriaceae_000000014592, the second column has been changed from G_0139 to G_0626, with suffixes ranging from 000000000001 to 000000000077.


The following is code that I used to explore the data. It will be difficult for anyone to follow, but I thought it would be worth saving in case I needed it in the future. 

```{bash}
selected_name_conv=DATA/meningitidis_gonorrhoeae-selected_name_conversions.txt
PROJECT_REPORT=$DIR_Contigs/${projectID}.report.tsv
BINNING=$DIR_Contigs/${projectID}.binning.tsv


cat $PROJECT_REPORT 

N_meningitidis_str_34279_id_GCA_003994995_1 G_0075 
N_meningitidis_str_NmJX80281_id_GCA_003996495_1 G_0082 
N_meningitidis_str_NmLN95_id_GCA_003996235_1 G_0090
N_meningitidis_str_NmLN16_id_GCA_003996475_1 G_0105
N_meningitidis_str_11059_id_GCA_003994965_1 G_0121
N_meningitidis_str_Nm360527_id_GCA_003995995_1 G_0139
N_meningitidis_str_420718_id_GCA_001183325_1 G_0204
N_meningitidis_str_Neisseria_meningitidis_id_GCA_900200365_1 G_0480

cat $PROJECT_REPORT | grep "G_0075"

cat $PROJECT_REPORT | grep "G_0121"

cat $PROJECT_REPORT | grep "G_0139"




#I need to update the PROJECT_REPORT so that the meningitidis genome IDs match the new genome IDs, 
#and then do the same in the binning file... 
# Then I can make the DECOMPOSE file properly, which relies on the new genome IDs


#So, first make copies of the $BINNING and $PROJECT_REPORT files

projectID=P_0003_Neisseriaceae
mainDIR=/workspace/jmarkwelchlab
DIR_Assemblies=02_ASSEMBLIES
DIR_Contigs=03_GENOMES_EDITED
DIR_ContigsDB=04_CONTIGS_DB
G_0213_genomesID=$mainDIR/$projectID/DATA/id_genomes-G_0213.txt
RAW_ASSEMBLY=$DIR_Assemblies/${projectID}-RAW.fa
PROJECT_CONTIGS=$DIR_Contigs/${projectID}.fa
PROJECT_REPORT=$DIR_Contigs/${projectID}.report.tsv
BINNING=$DIR_Contigs/${projectID}.binning.tsv
DECOMPOSE=$DIR_Contigs/${projectID}.decompose.tsv
CONTIGS_DB=$DIR_ContigsDB/${projectID}-contigs.db
minContigSIZE=300
G_0213_name_conv=$mainDIR/$projectID/DATA/G_0213-name_conversions.txt
selected_name_conv=DATA/meningitidis_gonorrhoeae-selected_name_conversions.txt
selected_new_name_conv=DATA/meningitidis_gonorrhoeae-selected_new_name_conversions.txt
PROJECT_REPORT_copy=$DIR_Contigs/${projectID}.report_copy.tsv
BINNING_copy=$DIR_Contigs/${projectID}.binning_copy.tsv

cp $BINNING $BINNING_copy
cp $PROJECT_REPORT $PROJECT_REPORT_copy


#Then change $PROJECT_REPORT_copy

# The command below shows that from P_0003_Neisseriaceae_000000013964 to P_0003_Neisseriaceae_000000014103 the suffix of the second column from G_0075_000000000001 to G_0075_000000000140 needs to be adjusted to G_0621, G_0621_000000000001 to G_0621_000000000140

cat $PROJECT_REPORT | grep "G_0075"
cat $selected_new_name_conv | grep "N_meningitidis_str_34279_id_GCA_003994995_1"
#G_0621

cat $PROJECT_REPORT | grep "G_0121"
cat $selected_new_name_conv | grep "N_meningitidis_str_11059_id_GCA_003994965_1"
#G_0625


cat $PROJECT_REPORT | grep "G_0139"
cat $selected_new_name_conv | grep "N_meningitidis_str_Nm360527_id_GCA_003995995_1"
#G_0626


scp -r jgiacomini@evol5.mbl.edu:/workspace/jmarkwelchlab/P_0003_Neisseriaceae/03_GENOMES_EDITED/P_0003_Neisseriaceae.report_copy.tsv .


cat $selected_new_name_conv | grep "N_gonorrhoeae_str_NCTC13799_id_GCA_900186935_1"

pangenomeID old_genomeID new_genomeID
N_meningitidis_str_NmJX80281_id_GCA_003996495_1 G_0082 G_0622
N_meningitidis_str_NmLN95_id_GCA_003996235_1 G_0090 G_0623
N_meningitidis_str_NmLN16_id_GCA_003996475_1 G_0105 G_0624
N_meningitidis_str_420718_id_GCA_001183325_1 G_0204 G_0627
N_meningitidis_str_Neisseria_meningitidis_id_GCA_900200365_1 G_0480 G_0628
N_meningitidis_str_Neisseria_meningitidis_id_GCA_900202155_1 G_0686  G_0629
N_meningitidis_str_N_61_16_id_GCA_015828755_1 G_1219 G_0630
N_meningitidis_str_108096_id_GCA_019350075_1 G_1462 G_0631
N_meningitidis_str_Neisseria_meningitidis_id_GCA_900200375_1 G_1721 G_0632
N_meningitidis_str_M38799_id_GCA_003490745_1 G_1921 G_0633
N_meningitidis_str_M40525_id_GCA_003493885_1 G_2816 G_0634
N_meningitidis_str_M40549_id_GCA_003492885_1 G_2867 G_0635
N_meningitidis_str_93004_id_GCA_000293245_1 G_2953 G_0636
N_meningitidis_str_ATCC_13091_id_GCA_000146655_1 G_2986 G_0637
N_meningitidis_str_93003_id_GCA_000293265_1 G_3005 G_0638
N_meningitidis_str_M22425_id_GCA_003355395_1 G_3160 G_0639
N_meningitidis_str_NCTC10025_id_GCA_900638555_1 G_3198 G_0640
N_gonorrhoeae_str_NCTC13799_id_GCA_900186935_1 G_3314 G_0641


```


# Send modified file back to barhal

Now we need to update the modified decomposition file...

```{bash, eval=FALSE}

# Run on Local
scp -r /Users/home/SPECIES_LEVEL_PANGENOMES/Neisseriaceae/P_0003_Neisseriaceae.report_modified.tsv jgiacomini@evol5.mbl.edu:/workspace/jmarkwelchlab/P_0003_Neisseriaceae/03_GENOMES_EDITED/P_0003_Neisseriaceae.report_modified.tsv


# Run on Barhal
sed -i -e 's/G_0082/G_0622/' -e 's/G_0090/G_0623/' -e 's/G_0105/G_0624/' -e 's/G_0204/G_0627/' -e 's/G_0480/G_0628/' -e 's/G_0686/G_0629/' -e 's/G_1219/G_0630/' -e 's/G_1462/G_0631/' -e 's/G_1721/G_0632/' -e 's/G_1921/G_0633/' -e 's/G_2816/G_0634/' -e 's/G_2867/G_0635/' -e 's/G_2953/G_0636/' -e 's/G_2986/G_0637/' -e 's/G_3005/G_0638/' -e 's/G_3160/G_0639/' -e 's/G_3198/G_0640/' -e 's/G_3314/G_0641/' 03_GENOMES_EDITED/P_0003_Neisseriaceae.report_modified.tsv

tail 03_GENOMES_EDITED/P_0003_Neisseriaceae.report_modified.tsv


PROJECT_REPORT_modified=03_GENOMES_EDITED/P_0003_Neisseriaceae.report_modified.tsv
BINNING_modified=03_GENOMES_EDITED/P_0003_Neisseriaceae.binning_modified.tsv
DECOMPOSE_modified=03_GENOMES_EDITED/P_0003_Neisseriaceae.decompose_modified.tsv

# Binning and decomposition files
cat $PROJECT_REPORT_modified | awk -F'_' -v OFS="_" 'NF{--NF};1' > $BINNING_modified

while IFS= read -r line
do
intGenomeID=$( echo "$line" | awk '{print $2}' )
newBinID=$( echo "$line" | awk '{print $1}' )
grep "$intGenomeID" $BINNING_modified | sed -e "s/$intGenomeID/$newBinID/" >> $DECOMPOSE_modified
done < $G_0213_name_conv
```

